In [294]:
import pandas as pd 
import numpy as np

from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import roc_auc_score

from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

# Carregando o arquivo

In [295]:

df = np.loadtxt('winequality.csv', delimiter=',', skiprows = 1)
display(df)

array([[7.40, 0.70, 0.00, ..., 0.56, 9.40, 5.00],
       [7.80, 0.88, 0.00, ..., 0.68, 9.80, 5.00],
       [7.80, 0.76, 0.04, ..., 0.65, 9.80, 5.00],
       ...,
       [6.30, 0.51, 0.13, ..., 0.75, 11.00, 6.00],
       [5.90, 0.65, 0.12, ..., 0.71, 10.20, 5.00],
       [6.00, 0.31, 0.47, ..., 0.66, 11.00, 6.00]])

#Mostrando as linhas e colunas do df


In [296]:
df.shape

(1599, 12)

#Transformado em um problema de classificação binária


In [297]:
df[df[:, -1] < 5.5, -1] = 0
df[df[:, -1] >= 5.5, -1] = 1

#Primeiras 10 linhas


In [298]:
np.set_printoptions(formatter={'float': '{:0.2f}'.format})
df[:10]

array([[7.40, 0.70, 0.00, 1.90, 0.08, 11.00, 34.00, 1.00, 3.51, 0.56,
        9.40, 0.00],
       [7.80, 0.88, 0.00, 2.60, 0.10, 25.00, 67.00, 1.00, 3.20, 0.68,
        9.80, 0.00],
       [7.80, 0.76, 0.04, 2.30, 0.09, 15.00, 54.00, 1.00, 3.26, 0.65,
        9.80, 0.00],
       [11.20, 0.28, 0.56, 1.90, 0.07, 17.00, 60.00, 1.00, 3.16, 0.58,
        9.80, 1.00],
       [7.40, 0.70, 0.00, 1.90, 0.08, 11.00, 34.00, 1.00, 3.51, 0.56,
        9.40, 0.00],
       [7.40, 0.66, 0.00, 1.80, 0.07, 13.00, 40.00, 1.00, 3.51, 0.56,
        9.40, 0.00],
       [7.90, 0.60, 0.06, 1.60, 0.07, 15.00, 59.00, 1.00, 3.30, 0.46,
        9.40, 0.00],
       [7.30, 0.65, 0.00, 1.20, 0.07, 15.00, 21.00, 0.99, 3.39, 0.47,
        10.00, 1.00],
       [7.80, 0.58, 0.02, 2.00, 0.07, 9.00, 18.00, 1.00, 3.36, 0.57,
        9.50, 1.00],
       [7.50, 0.50, 0.36, 6.10, 0.07, 17.00, 102.00, 1.00, 3.35, 0.80,
        10.50, 0.00]])

#Transformandos os parâmetros(X) e a classe(Y) do df em arrays

In [299]:
X = df[:, :-1]

Y = df[:, -1]

#Normalizando os dados


In [300]:
mean = X.mean(axis = 0)

In [301]:
#
X -= mean

In [302]:
std = X.std(axis = 0)

In [303]:
X /= std

#Construindo o modelo
- Criando os layers
- Oito neurons
- Dim dinâmico
- Relu, ativação não linear

In [304]:
model = Sequential()

model.add(Dense(8, input_dim = len(X[0, :]), activation = 'relu'))
model.add(Dense(4, activation = 'relu'))
model.add(Dense(1, activation = 'sigmoid'))

#Vizualização do modelo


In [305]:
model.summary()

Model: "sequential_24"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_67 (Dense)            (None, 8)                 96        
                                                                 
 dense_68 (Dense)            (None, 4)                 36        
                                                                 
 dense_69 (Dense)            (None, 1)                 5         
                                                                 
Total params: 137
Trainable params: 137
Non-trainable params: 0
_________________________________________________________________


#Compilando o modelo
Loss para a binary cross entropy

In [306]:
model.compile(loss = 'binary_crossentropy', optimizer = 'rmsprop', metrics=['accuracy'])

#Realizando o treinamento


In [307]:
model.fit(x  = X, y = Y, epochs = 256, verbose = 1)

Epoch 1/256
50/50 [==============================] - 1s 3ms/step - loss: 0.7089 - accuracy: 0.4853
Epoch 2/256
50/50 [==============================] - 0s 2ms/step - loss: 0.6818 - accuracy: 0.5403
Epoch 3/256
50/50 [==============================] - 0s 2ms/step - loss: 0.6563 - accuracy: 0.6091
Epoch 4/256
50/50 [==============================] - 0s 2ms/step - loss: 0.6311 - accuracy: 0.6529
Epoch 5/256
50/50 [==============================] - 0s 2ms/step - loss: 0.6087 - accuracy: 0.6848
Epoch 6/256
50/50 [==============================] - 0s 2ms/step - loss: 0.5888 - accuracy: 0.7017
Epoch 7/256
50/50 [==============================] - 0s 2ms/step - loss: 0.5722 - accuracy: 0.7161
Epoch 8/256
50/50 [==============================] - 0s 2ms/step - loss: 0.5574 - accuracy: 0.7205
Epoch 9/256
50/50 [==============================] - 0s 2ms/step - loss: 0.5462 - accuracy: 0.7161
Epoch 10/256
50/50 [==============================] - 0s 2ms/step - loss: 0.5382 - accuracy: 0.7192
Epoch 11/

#Loss caindo é um bom sinal. Significa que o treinamento está funcionando

In [308]:
prediction = model.predict(X)

50/50 [==============================] - 0s 1ms/step


#Probabilidade para os 5 primeiros data points


In [309]:
prediction[:5]

array([[0.14],
       [0.32],
       [0.28],
       [0.33],
       [0.14]], dtype=float32)

In [310]:
Y[:5]

array([0.00, 0.00, 0.00, 1.00, 0.00])

Acurácia

In [311]:
my_accuracy = accuracy_score(Y, prediction.round())
my_accuracy

0.7898686679174484

Baseline

In [312]:
len(Y)

1599

Quantos dos valores são positivos


In [313]:
Y.sum()

855.0

55% são positivos, ou seja, bons vinhos



In [314]:
855 / 1599

0.5347091932457786

Precisão

In [315]:

precision = precision_score(Y, prediction.round())
precision

0.8153098420413123

Kappa

In [316]:

kappa = cohen_kappa_score(Y, prediction.round())
print('Cohens kappa: %f' % kappa)

Cohens kappa: 0.578878


F1

In [317]:

f1 = f1_score(Y, prediction.round())
print('F1 score: %f' % f1)

F1 score: 0.799762


Recall

In [318]:
recall = recall_score(Y, prediction.round())
print('Recall: %f' % recall)

Recall: 0.784795


ROC AUC

In [319]:
auc = roc_auc_score(Y, prediction.round())
print('ROC AUC: %f' % auc)

ROC AUC: 0.790247
